### ISSUE TITLE
select/input/textarea默认的box-sizing不一样

### ISSUE THREAD

**Issue by 2ue** [hangyangws/baseCss#1]
select/input/textarea默认的box-sizing不一样，在baseCss中统一处理了更好

**Comment by hangyangws** [comment]
谢谢提醒，我糊涂得把这个忘了。

**Comment by 2ue** [comment]
忘了说了，还有一个我以前遇到的问题。是关于css开头UTF-8编码的。
https://www.zhihu.com/question/34581699

**Comment by hangyangws** [comment]
恩，我个人觉得还是写上好。
毕竟本css文件中出现了中文。
而html文件类型统一‘utf-8’，应该是很多开发者的共识了。

谢谢。

**Comment by 2ue** [comment]
只是我以前遇到过加了utf-8出现乱码，所以后来索性不加了。

**Comment by hangyangws** [comment]
就想你刚刚提发的知乎的链接一样，乱码无非就那么几种原因。
我觉得可写可不写，我也看到很多人不喜欢写，没有对错，这个。
^_^
(要不github互粉一下)

**Comment by 2ue** [comment]
是的，其实只要多注意一下，加不加都无所谓了。
已粉~
